### ISSUE TITLE
performance problem

### ISSUE THREAD

**Issue by spfan** [JALBAA/vue-lazyload-img#15]
`window.addEventListener('scrollEnd', () => {}) ` will execute too many time when the page has a lot of img.

**Comment by wormsan** [comment]
I'll test it later when I have time, and  if you have a better way to judge when the scrolling movement is done. I'll appreciate if you pull a request.

**Comment by wormsan** [comment]
In v2.1.0 I had removed these liseners, and there were only 2 liseners now.
