### ISSUE TITLE
使用webpack打包，引入之后报错

### ISSUE THREAD

**Issue by rvrfox** [JALBAA/vue-lazyload-img#21]
版本：2.1.2
使用Babel报：
`"export 'default' (imported as 'Lazyload') was not found in 'vue-lazyload-img'`

不使用Babel报：
`vue.lazyimg.js?73fa:170 Uncaught TypeError: Cannot read property 'time' of undefined
    at Object.install (vue.lazyimg.js?73fa:170)
    at Function.Vue.use (`

**Comment by wormsan** [comment]
hi，我这边新启动了一个项目试了一些，2.1.2可以使用babel打包。
分别使用了webpack@3，babel-preset-env。
麻烦提供一下更多的信息，包括.babelrc，package.json，webpack.config.js的配置。

**Comment by rvrfox** [comment]
`      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules\/swiper'), resolve('node_modules\/dom7'), resolve('node_modules\/vue-lazyload-img')]
      },`

`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}
`


`{
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "npm run dev",
    "build": "node build/build.js",
    "lint": "eslint --ext .js,.vue src"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "fundebug-javascript": "^0.3.6",
    "graphql": "^0.13.1",
    "hls.js": "^0.8.9",
    "mta-h5-analysis": "^2.0.9",
    "promise-polyfill": "^6.1.0",
    "raven-js": "^3.24.2",
    "underscore": "^1.8.3",
    "vue": "^2.5.2",
    "vue-awesome-swiper": "^3.0.4",
    "vue-bus": "^1.0.0",
    "vue-cropperjs": "^2.2.0",
    "vue-dplayer": "0.0.5",
    "vue-lazyload-img": "^2.1.2",
    "vue-progressbar": "^0.7.3",
    "vue-router": "^3.0.1",
    "weixin-js-sdk": "1.2.0",
    "whatwg-fetch": "^2.0.3"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^2.0.1",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb-base": "^11.1.3",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^3.0.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "http-proxy-middleware": "^0.17.3",
    "less": "^2.7.2",
    "less-loader": "^4.0.5",
    "opn": "^5.1.0",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-hot-middleware": "^2.18.2",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
`

**Comment by wormsan** [comment]
hi,
首先babel报出的是个警告，不影响使用。
导致这个问题的原因是：`vue-lazyload-img`使用了`umd`形式进行导出，且2.1.2后使用了`typescript`进行了部分重写，默认入口现在改为了`dsit/vue.lazyimg.js`，仅支持`amd`、`commonjs`、`var`形式的调用。
你这边`.babelrc`中有个配置，`modules: false`，详情参见[babel文档](http://babeljs.io/docs/plugins/preset-es2015/#modules)，而你使用了import，所以babel会以`esm`的形式进行加载，故有此提示。
解决方案：
1. 使用`commonjs`的格式进行加载，`const Lazyload = require('vue-lazyload-img')` （**推荐**）
2. 将`.babelrc`中的`modules:false`删除（**全局改动，可能造成未知问题，不推荐**）
3. 放置不管（**并不会影响代码逻辑**）
4. 回退到2.1.1版本（**老版本是以esm形式导出的**）
5. 使你的工程支持`typescript`，然后`import Lazyload from 'vue-lazyload-img/src/lib/index'`，即使用ts入口亦可（**太麻烦，不推荐**）

**Comment by rvrfox** [comment]
还是建议node-module里的代码是不需要用户用babel转化的。要不然用户容易遇到这种问题。
绝大部分npm包都是这样的。

**Comment by wormsan** [comment]
回头看看怎么适配，主要umd和esm不太兼容。
