### ISSUE TITLE
当为单页面应用的时候，如果路由到另一没有使用懒加载的页面，会报错

### ISSUE THREAD

**Issue by ykx456654** [JALBAA/vue-lazyload-img#4]
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null`

需要在 compute方法执行的时候进行判断， this.el != undefined

**Comment by whwnow** [comment]
这个github上的版本时有的，但是npm没更新，落后了……

**Comment by wormsan** [comment]
已经提交npm

**Comment by wormsan** [comment]
v1基本放弃了，v2对router做了较好的处理，如果还需要对v1修复的话，欢迎直接提交merge request
