### ISSUE TITLE
数据变化时，未初始化加载

### ISSUE THREAD

**Issue by jesse-li** [JALBAA/vue-lazyload-img#6]
图片数据变化时，懒加载出现问题 如：
list[1,2,3]  第一次显示全部 第二次根据相应的操作显示[2,3],此时真实图片地址未替换

**Comment by wormsan** [comment]
和#7 #3应该是类似问题，dom刷新后el为空，需要再看下vue机制，近期尽快修复=。=

**Comment by wormsan** [comment]
v1基本放弃了，v2对router做了较好的处理，如果还需要对v1修复的话，欢迎直接提交merge request
